{{- if not .Values.global.enterprise  }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kafka-topics-ui.fullname" . }}
  labels:
    app: {{ template "kafka-topics-ui.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "kafka-topics-ui.name" . }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "kafka-topics-ui.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.global.private_registry.enabled }}
          image: "{{ .Values.global.private_registry.path }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          env:
          - name: KAFKA_REST_PROXY_URL
            value: {{ template "kafka-rest-proxy.name" . }}
          - name: PROXY
            value: "true"
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
{{- end }}
