name: rabbitmq
apiVersion: v1
appVersion: 3.8.5
version: 1.46.4
description: Highly available RabbitMQ cluster, the open source message broker
  software that implements the Advanced Message Queuing Protocol (AMQP).
keywords:
- rabbitmq
- message queue
- AMQP
- AMQPS
- MQTT
- STOMP
home: https://www.rabbitmq.com
icon: file://../logo-rabbitmq.png
sources:
- https://github.com/rabbitmq/rabbitmq
- https://github.com/docker-library/rabbitmq
maintainers:
- name: steven-sheehy
