# Default values for efk.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
elasticsearch:
  enabled: true
  image: "ranchercharts/elasticsearch-elasticsearch"
  imageTag: "7.3.0"
  enableProxy: true

kibana:
  enabled: true
  image: "ranchercharts/kibana-kibana"
  imageTag: "7.3.0"
  server:
    basePath: ""

filebeat:
  enabled: false
  image: "ranchercharts/beats-filebeat"
  imageTag: "7.3.0"

metricbeat:
  enabled: false
  image: "ranchercharts/beats-metricbeat"
  imageTag: "7.3.0"
  kube-state-metrics:
    image:
      repository: ranchercharts/coreos-kube-state-metrics
      tag: v1.7.2

global:
  nginxProxy:
    repository: rancher/nginx
    tag: 1.15.8-alpine
  private_registry:
    enabled: false
    path: