apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ template "cassandra.name" . }}
  labels:
    app: {{ template "cassandra.name" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ template "cassandra.name" . }}
    release: {{ .Release.Name }}
  replicas: {{ .Values.config.cluster_size }}
  template:
    metadata:
      labels:
        app: {{ template "cassandra.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - command:
            - /run.sh
          resources:
            limits:
              cpu: 0.5
          name: {{ template "cassandra.name" . }}
          image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
          env:
            - name: CASSANDRA_SEEDS
              value: 1
            - name: MAX_HEAP_SIZE
              value: {{ default "8192M" .Values.config.max_heap_size | quote }}
            - name: HEAP_NEWSIZE
              value: {{ default "200M" .Values.config.heap_new_size | quote }}
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: {{ default "SimpleSnitch" .Values.config.endpoint_snitch | quote }}
            - name: CASSANDRA_CLUSTER_NAME
              value: {{ default "Cassandra" .Values.config.cluster_name | quote }}
            - name: CASSANDRA_DC
              value: {{ default "DC1" .Values.config.dc_name | quote }}
            - name: CASSANDRA_RACK
              value: {{ default "RAC1" .Values.config.rack_name | quote }}
            - name: CASSANDRA_START_RPC
              value: {{ default "false" .Values.config.start_rpc | quote }}
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: intra
              containerPort: 7000
            - name: tls
              containerPort: 7001
            - name: jmx
              containerPort: 7199
            - name: cql
              containerPort: {{ default 9042 .Values.config.ports.cql }}
            - name: thrift
              containerPort: {{ default 9160 .Values.config.ports.thrift }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/cassandra
      volumes:
        - name: data
          emptyDir: {}

